let skills = [
  {skill: 'Web Development', tools:'VS Code, Bootstrap, Git, GitHub, Azure DevOps, Django, PIP & NPM Package managers', languages: 'HTML, CSS, JS, jQuery, TypeScript, REST APIs, React, & Python', description: ''},
  {skill: 'SharePoint & O365 Development', tools: 'SharePoint Design 2010, 2013 & 2016, DataTables.net, VSCode, PowerBI, InfoPath 2013, PowerApps, Flow, SQL Management Studio', languages: 'SQL, HTML, CSS, jQuery, psuedocode, & client side JS', description: ''},
  {skill: 'Reporting & Data Visualization', tools: 'PowerBI, Excel, Bootstrap, DataTables.net, D3.js, Google Charts, Crystal Reports', languages: 'JavaScript, jQuery, Python, PowerShell', description: ''},
  {skill: 'Mobile App Development', tools: 'VS Code, Expo, React Native, Xcode, Android Studio, Yarn Package Manager, JEST, Azure DevOps, GitHub, Git', languages: 'Swift, Objective-C, React Native, JSX, Java, REST APIs', description:''},
  {skill: 'Technical Writing & Training', tools: 'Microsoft Office, Notion, Zoom, GoToMeeting, Skype, Slack', languages: 'Written & Spoken English', description: ''},
]

  let skillList = [
    {skill: 'HTML / CSS', icon: ''},
    {skill: 'Design & Layout', icon: ''},
    {skill: 'InfoPath', icon: ''},
    {skill: 'JavaScript / jQuery / TypeScript', icon: ''},
    {skill: 'Microsoft Office', icon: ''},
    {skill: 'Microsoft PowerApps & Flow', icon: ''},
    {skill: 'Microsoft Server 2008 & 2012', icon: ''},
    {skill: 'Microsoft SQL Server', icon: ''},
    {skill: 'PIP Package Manager', icon: ''},
    {skill: 'PowerBI', icon: ''},
    {skill: 'Crystal Reports', icon: ''},
    {skill: 'PowerShell', icon: ''},
    {skill: 'Python & Django', icon: ''},
    {skill: 'React Native', icon: ''},
    {skill: 'React', icon: ''},
    {skill: 'Redux', icon: ''},
    {skill: 'REST API Data Integration', icon: ''},
    {skill: 'SharePoint 2010, 2013, 2016 & Online', icon: ''},
    {skill: 'Technical Customer Service', icon: ''},
    {skill: 'Technical Writing', icon: ''},
    {skill: 'Yarn & Node Package Managers', icon: ''},
    {skill: 'UI / UX Development', icon: ''},
]