let skills = [
  'HTML / CSS',
  'Design & Layout',
  'InfoPath',
  'JavaScript / jQuery / TypeScript',
  'Microsoft Office',
  'Microsoft PowerApps & Flow',
  'Microsoft Server 2008 & 2012',
  'Microsoft SQL Server',
  'PIP Package Manager',
  'PowerBI',
  'Crystal Reports',
  'PowerShell',
  'Python & Django',
  'React Native',
  'React',
  'Redux',
  'REST API Data Integration',
  'SharePoint 2010, 2013, 2016 & Online',
  'Technical Customer Service',
  'Technical Writing',
  'Yarn & Node Package Managers',
  'UI / UX Development',
]